name: Run tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: 
      - "main"

jobs:
  example-1:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.6", "3.7", "3.8"]

    steps:
      - uses: actions/checkout@v2
      - name: Cache Conda
        uses: actions/cache@v1
        with:
          path: /usr/share/miniconda/envs/ledgerx
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-
      - name: Setup conda dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ledgerx
          environment-file: environment.yml
          python-version: "${{ matrix.python-version }}"
          auto-activate-base: false
      - name: Conda info
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest
